[2021-01-15 13:48:14,463::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID220164:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-01-15 13:48:14,464::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID220164:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-01-15 13:48:14,464::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID220164:MainProcess): DNS Resolver Port: 53
[2021-01-15 13:48:14,464::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID220164:MainProcess): DNS Resolver timeout: 2.0
[2021-01-15 13:48:14,464::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID220164:MainProcess): DNS Resolver lifetime: 5.0
[2021-01-15 13:48:14,464::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID220164:MainProcess): DNS Resolver over TCP: False
[2021-01-15 14:04:04,189::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID338482:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-01-15 14:04:04,189::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID338482:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-01-15 14:04:04,190::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID338482:MainProcess): DNS Resolver Port: 53
[2021-01-15 14:04:04,190::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID338482:MainProcess): DNS Resolver timeout: 2.0
[2021-01-15 14:04:04,190::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID338482:MainProcess): DNS Resolver lifetime: 5.0
[2021-01-15 14:04:04,190::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID338482:MainProcess): DNS Resolver over TCP: False
[2021-01-16 10:25:21,637::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID918448:MainProcess): DNS Resolver Nameservers: ['2a01:4f8:0:1::add:9898', '213.133.98.98', '2a01:4f8:0:1::add:9999', '213.133.99.99', '2a01:4f8:0:1::add:1010', '213.133.100.100']
[2021-01-16 10:25:21,637::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID918448:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-01-16 10:25:21,637::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID918448:MainProcess): DNS Resolver Port: 53
[2021-01-16 10:25:21,638::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID918448:MainProcess): DNS Resolver timeout: 2.0
[2021-01-16 10:25:21,638::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID918448:MainProcess): DNS Resolver lifetime: 5.0
[2021-01-16 10:25:21,638::DEBUG::/home/mitchellkrog/.conda/envs/diffcheck/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID918448:MainProcess): DNS Resolver over TCP: False
